<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <Version Condition="'$(Version)' == ''">2.1.0</Version>
        <Authors>Alan Lira</Authors>
        <Description>Extensions of Flunt for Brazilian projects</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/lira92/flunt.br</PackageProjectUrl>
        <RepositoryUrl>https://github.com/lira92/flunt.br</RepositoryUrl>
        <PackageIcon>flunt-icon-br_compressed.png</PackageIcon>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <PackageTags>Validation;Flunt.Br;Flunt;Cnpj;Cpf;Telefone;Cep</PackageTags>
    </PropertyGroup>

    <ItemGroup Label="Flunt">
        <PackageReference Include="Flunt" Version="2.0.3"/>
    </ItemGroup>

    <ItemGroup Label="Package Assets">
        <None Include="..\..\assets\flunt-icon-br_compressed.png">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
            <Link>flunt-icon-br_compressed.png</Link>
        </None>
        <None Include="..\..\Readme.md">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
            <Link>Readme.md</Link>
        </None>
    </ItemGroup>
</Project>
