version: 1.0.{build}
image: Ubuntu1804
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: >-
    dotnet restore
    
    dotnet build
build:
  verbosity: minimal
